
name: Terraform Backend (AWS)
label: Terraform Backend (AWS)
description: Creates a Terraform backend with state locking in AWS S3 and DynamoDB.
type: terraform
extends:

labels:
  collection: Terraform Backends

variables:
  - name: aws_access_key_id
    description: AWS Access Key
    type_hint: password
  - name: aws_secret_access_key
    description: AWS Secret Key
    type_hint: password
  - name: aws_region
    description: AWS Region
    default: choices
    type_hint: dropdown
    dd_list:
      - key: ap-northeast-1
        value: ap-northeast-1
      - key: ap-northeast-2
        value: ap-northeast-2
      - key: ap-south-1
        value: ap-south-1
      - key: ap-southeast-1
        value: ap-southeast-1
      - key: ap-southeast-2
        value: ap-southeast-2
      - key: ca-central-1
        value: ca-central-1
      - key: eu-central-1
        value: eu-central-1
      - key: eu-north-1
        value: eu-north-1
      - key: eu-west-1
        value: eu-west-1
      - key: eu-west-2
        value: eu-west-2
      - key: eu-west-3
        value: eu-west-3
      - key: sa-east-1
        value: sa-east-1
      - key: us-east-1
        value: us-east-1
      - key: us-east-2
        value: us-east-2
      - key: us-west-1
        value: us-west-1
      - key: us-west-2
        value: us-west-2
